# Generated by Django 6.0.2 on 2026-10-03 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='club name')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='short name')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='tagline')),
                ('description', models.TextField(blank=True, verbose_name='club description')),
                ('category', models.CharField(default='Engineering & Technology', max_length=100, verbose_name='category')),
                ('badge', models.CharField(blank=True, default='Flagship Chapter', max_length=50, verbose_name='featured badge')),
                ('faculty_advisor', models.CharField(default='Dr. Alexander Vance (Faculty Advisor)', max_length=150, verbose_name='faculty advisor')),
                ('meeting_schedule', models.CharField(default='Tuesdays & Thursdays • 5:30 PM', max_length=255, verbose_name='meeting schedule')),
                ('banner_image', models.TextField(blank=True, default='https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80', verbose_name='club banner url')),
                ('semester_fee', models.DecimalField(decimal_places=2, default=299.0, max_digits=10, verbose_name='semester membership fee')),
                ('annual_fee', models.DecimalField(decimal_places=2, default=499.0, max_digits=10, verbose_name='annual membership fee')),
                ('available_spots', models.PositiveIntegerField(default=35, verbose_name='available spots')),
                ('total_spots', models.PositiveIntegerField(default=150, verbose_name='total spots')),
                ('benefits', models.JSONField(blank=True, default=list, verbose_name='member benefits list')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.CharField(editable=False, max_length=60, primary_key=True, serialize=False)),
                ('club_name_snapshot', models.CharField(blank=True, max_length=200, verbose_name='club name snapshot')),
                ('membership_type', models.CharField(choices=[('SEMESTER', 'Semester'), ('ANNUAL', 'Annual')], default='ANNUAL', max_length=20, verbose_name='membership type')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='membership fee paid')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='expiry date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(default='Student Account (Bursar)', max_length=100, verbose_name='payment method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='receipt / transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Club Membership',
                'verbose_name_plural': 'Club Memberships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, default='https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=250&q=80', verbose_name='avatar image url'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='Computer Science & Software Engineering', max_length=150, verbose_name='department / major'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='membership expiry date'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='membership start date'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('NONE', 'None'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='NONE', max_length=20, verbose_name='membership status'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('SEMESTER', 'Semester'), ('ANNUAL', 'Annual')], max_length=20, null=True, verbose_name='membership type'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='+1 (555) 234-8910', max_length=30, verbose_name='contact phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.CharField(blank=True, default='Semester 4 • 2026', max_length=50, verbose_name='academic semester'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('MEMBER', 'Member'), ('ADMIN', 'Admin'), ('TREASURER', 'Treasurer')], default='STUDENT', max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='Unique university student ID. Required for student members.', max_length=50, null=True, unique=True, verbose_name='student ID'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['membership_status'], name='accounts_us_members_832832_idx'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.club'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
