# Generated by Django 5.2.17 on 2026-10-03 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_club_clubmembership_user_avatar_user_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('REMINDER_30_DAYS', '30 Days Expiry Reminder'), ('REMINDER_7_DAYS', '7 Days Expiry Reminder'), ('REMINDER_1_DAY', '1 Day Expiry Reminder'), ('REMINDER_CUSTOM', 'Custom Expiry Reminder'), ('MEMBERSHIP_EXPIRED', 'Membership Expired / Due Notice')], max_length=50, verbose_name='notification type')),
                ('target_expiry_date', models.DateField(blank=True, help_text='Expiry date for which the reminder/notice was dispatched.', null=True, verbose_name='target expiry date')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='recipient email address')),
                ('status', models.CharField(choices=[('SENT', 'Sent Successfully'), ('FAILED', 'Failed')], default='SENT', max_length=20, verbose_name='delivery status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership Notification Log',
                'verbose_name_plural': 'Membership Notification Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'notification_type', 'target_expiry_date'], name='accounts_me_user_id_e2dafc_idx'), models.Index(fields=['sent_at'], name='accounts_me_sent_at_b3e73b_idx')],
            },
        ),
    ]
