# Generated by Django 5.2.17 on 2026-10-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membershipnotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipnotificationlog',
            name='reference_id',
            field=models.CharField(blank=True, default='', help_text='Unique reference such as ticket_id, order_id, or payment_id to prevent duplicates.', max_length=100, verbose_name='payment or item reference ID'),
        ),
        migrations.AlterField(
            model_name='membershipnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('REMINDER_30_DAYS', '30 Days Expiry Reminder'), ('REMINDER_7_DAYS', '7 Days Expiry Reminder'), ('REMINDER_1_DAY', '1 Day Expiry Reminder'), ('REMINDER_CUSTOM', 'Custom Expiry Reminder'), ('MEMBERSHIP_EXPIRED', 'Membership Expired / Due Notice'), ('PAYMENT_EVENT_TICKET', 'Event Ticket Payment Success'), ('PAYMENT_MERCHANDISE', 'Merchandise Payment Success')], max_length=50, verbose_name='notification type'),
        ),
        migrations.AddIndex(
            model_name='membershipnotificationlog',
            index=models.Index(fields=['user', 'notification_type', 'reference_id'], name='accounts_me_user_id_f7467a_idx'),
        ),
    ]
