# Generated by Django 5.2.17 on 2026-10-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_membershipnotificationlog_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='website_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='club resource link'),
        ),
    ]
