# Generated by Django 6.0.2 on 2026-10-03 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_volunteers',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=150, verbose_name='attendee capacity'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='17:00:00', verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Flagship Event', 'Flagship Event'), ('Technical Workshop', 'Technical Workshop'), ('Hackathon', 'Hackathon'), ('Career & Networking', 'Career & Networking'), ('Social & Culture', 'Social & Culture'), ('Seminar & Lecture', 'Seminar & Lecture'), ('General Event', 'General Event')], default='Flagship Event', max_length=100, verbose_name='event type'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.TextField(blank=True, default='https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80', verbose_name='event banner url'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='14:00:00', verbose_name='start time'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Published', max_length=20, verbose_name='event status'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ticket price'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Student Union Auditorium', max_length=255, verbose_name='venue / location'),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteer_count_required',
            field=models.PositiveIntegerField(default=0, verbose_name='volunteer count required'),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteer_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='volunteer deadline'),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteer_roles_required',
            field=models.TextField(blank=True, default='Registration Desk, Photography Team, Technical Support, Stage Management, Hospitality, Event Coordinator', help_text='Comma-separated list of volunteer roles', verbose_name='volunteer roles required'),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteers_required',
            field=models.BooleanField(default=False, verbose_name='volunteers required'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='experience',
            field=models.TextField(blank=True, verbose_name='previous experience'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='preferred_role',
            field=models.CharField(default='General Volunteer', max_length=100, verbose_name='preferred role'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='reason',
            field=models.TextField(blank=True, verbose_name='why do you want to volunteer?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='legacy location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='event name'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='admin_feedback',
            field=models.TextField(blank=True, verbose_name='admin notes/feedback'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to='volunteers.event'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='notes',
            field=models.TextField(blank=True, verbose_name='legacy notes'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='application status'),
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_role', models.CharField(max_length=100, verbose_name='assigned volunteer role')),
                ('duration', models.CharField(default='4 Hours', max_length=100, verbose_name='duration')),
                ('notes', models.TextField(blank=True, verbose_name='assignment notes')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20, verbose_name='assignment status')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='approved at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='volunteers.volunteerapplication')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to='volunteers.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Volunteer Assignment',
                'verbose_name_plural': 'Volunteer Assignments',
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='certificate id')),
                ('volunteer_role', models.CharField(max_length=100, verbose_name='volunteer role')),
                ('duration', models.CharField(default='4 Hours', max_length=100, verbose_name='duration / hours')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='issue date')),
                ('verification_hash', models.CharField(blank=True, max_length=64, verbose_name='cryptographic verification hash')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='volunteers.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='volunteers.volunteerassignment')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date'],
                'unique_together': {('student', 'event')},
            },
        ),
    ]
