# Generated by Django 6.0.2 on 2026-10-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_alter_event_options_remove_event_max_volunteers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='event description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, default='Flagship Event', max_length=100, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='Student Union Auditorium', max_length=255, verbose_name='venue / location'),
        ),
    ]
