# Generated by Django 6.0.2 on 2026-10-03 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_event_description_alter_event_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='announcement title')),
                ('content', models.TextField(verbose_name='message body')),
                ('category', models.CharField(blank=True, default='General', max_length=100, verbose_name='category')),
                ('priority', models.CharField(blank=True, default='Normal', max_length=50, verbose_name='priority')),
                ('sent_to', models.CharField(blank=True, default='All Members', max_length=100, verbose_name='target audience')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='recipients count')),
                ('channels', models.JSONField(blank=True, default=list, verbose_name='delivery channels')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Sent', 'Sent'), ('Cancelled', 'Cancelled')], default='Sent', max_length=50, verbose_name='status')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='scheduled date')),
                ('scheduled_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='scheduled time')),
                ('timezone', models.CharField(blank=True, default='Organization Time Zone (IST)', max_length=100, verbose_name='timezone')),
                ('sent_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='sent date display')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at timestamp')),
                ('pinned', models.BooleanField(default=False, verbose_name='pinned notice')),
                ('allow_replies', models.BooleanField(default=True, verbose_name='allow replies')),
                ('author', models.CharField(blank=True, default='Dr. Alexander Vance (Faculty Advisor)', max_length=255, verbose_name='author display name')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='attachments')),
                ('delivery_stats', models.JSONField(blank=True, default=dict, verbose_name='delivery stats')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
    ]
