# Generated by Django 6.0.2 on 2026-10-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='member_ticket_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='member ticket price'),
        ),
        migrations.AddField(
            model_name='event',
            name='non_member_ticket_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='non-member ticket price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='ticket price (regular/non-member)'),
        ),
    ]
