# Generated by Django 6.0.2 on 2026-10-03 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_remove_volunteer_student_role_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='ticket ID')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Transferred', 'Transferred'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20, verbose_name='ticket status')),
                ('tier', models.CharField(default='Member Pass', max_length=50, verbose_name='ticket tier')),
                ('price_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price paid')),
                ('seat', models.CharField(blank=True, max_length=100, verbose_name='assigned seat')),
                ('gate', models.CharField(blank=True, default='Main Entrance (Gate 1)', max_length=100, verbose_name='assigned gate')),
                ('qr_code_data', models.CharField(blank=True, max_length=255, verbose_name='qr code payload')),
                ('transferred_to', models.CharField(blank=True, max_length=255, verbose_name='transferred to')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='volunteers.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Ticket',
                'verbose_name_plural': 'Event Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
