# Generated by Django 6.0.2 on 2026-10-03 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_merchandiseproduct_payment_merchandiseorder_and_more'),
        ('volunteers', '0007_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checked_in',
            field=models.BooleanField(db_index=True, default=False, verbose_name='checked in status'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='checked in timestamp'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/pdf/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='tickets/qr/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_token',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True, verbose_name='secure QR ticket token'),
        ),
    ]
