# Generated by Django 6.0.2 on 2026-10-03 22:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_ticket_checked_in_ticket_checked_in_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, verbose_name='ticket UUID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='secure QR ticket token'),
        ),
    ]
