# Generated by Django 6.0.2 on 2026-10-03 22:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_ticket_ticket_uuid_alter_ticket_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='ticket UUID'),
        ),
    ]
