# Generated by Django 6.0.2 on 2026-10-03 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_payment_finance_pay_razorpa_ab09a4_idx_and_more'),
        ('volunteers', '0010_alter_ticket_ticket_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Confirmed')), fields=('student', 'event'), name='unique_confirmed_ticket_per_student_event'),
        ),
    ]
