# Generated by Django 5.2.9 on 2026-10-03 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='claim title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='claim amount')),
                ('description', models.TextField(verbose_name='purpose and details')),
                ('receipt_reference', models.CharField(blank=True, max_length=255, verbose_name='receipt reference or URL')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('treasurer_notes', models.TextField(blank=True, verbose_name='treasurer notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reimbursements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reimbursement Request',
                'verbose_name_plural': 'Reimbursement Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='transaction title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='INCOME', max_length=10, verbose_name='type')),
                ('category', models.CharField(choices=[('MEMBERSHIP_FEE', 'Membership Fee'), ('SPONSORSHIP', 'Sponsorship'), ('EVENT_EXPENSE', 'Event Expense'), ('MERCHANDISE', 'Merchandise'), ('OPERATIONAL', 'Operational'), ('REIMBURSEMENT', 'Reimbursement'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date', models.DateField(verbose_name='transaction date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
