# Generated by Django 5.2.17 on 2026-10-03 19:47

import uuid

import django.core.validators
import django.db.models.deletion
import finance.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_transaction_ids(apps, schema_editor):
    Transaction = apps.get_model('finance', 'Transaction')
    for txn in Transaction.objects.all():
        if not txn.transaction_id:
            prefix = 'INC' if txn.transaction_type == 'INCOME' else 'EXP'
            txn.transaction_id = f'TXN-{prefix}-{uuid.uuid4().hex[:8].upper()}'
            txn.save(update_fields=['transaction_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('volunteers', '0004_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementrequest',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='volunteers.event'),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='linked_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_reimbursement', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='paid at'),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to=finance.models.receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='receipt file'),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='related_activity',
            field=models.CharField(blank=True, help_text='Free-text activity label when no Event FK is available.', max_length=200, verbose_name='event / fundraiser label'),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='party_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='student / customer / vendor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, help_text='Idempotency key for the originating payment or claim.', max_length=100, verbose_name='source reference ID'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('MEMBERSHIP', 'Membership Purchase'), ('EVENT_TICKET', 'Event Ticket Purchase'), ('MERCHANDISE', 'Merchandise Order'), ('FUNDRAISER', 'Fundraiser Payment'), ('REIMBURSEMENT', 'Reimbursement Payout'), ('MANUAL', 'Manual Entry'), ('REFUND', 'Refund Adjustment')], default='MANUAL', max_length=30, verbose_name='source reference type'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PAID', max_length=20, verbose_name='payment / ledger status'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Human-readable unique ledger ID (auto-generated if blank).', max_length=40, null=True, verbose_name='transaction ID'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.RunPython(backfill_transaction_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Human-readable unique ledger ID (auto-generated if blank).', max_length=40, unique=True, verbose_name='transaction ID'),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='claim amount'),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('MEMBERSHIP_FEE', 'Membership Fee'), ('EVENT_TICKET', 'Event Ticket'), ('MERCHANDISE', 'Merchandise'), ('FUNDRAISER', 'Fundraiser'), ('SPONSORSHIP', 'Sponsorship'), ('EVENT_EXPENSE', 'Event Expense'), ('FUNDRAISER_EXPENSE', 'Fundraiser Expense'), ('OPERATIONAL', 'Operational'), ('REIMBURSEMENT', 'Reimbursement'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reimbursementrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_reimbursement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id', ''), _negated=True), fields=('reference_type', 'reference_id'), name='uniq_finance_txn_reference'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_transaction_amount_positive'),
        ),
    ]
