# Generated by Django 6.0.2 on 2026-10-03 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchandiseProduct',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='item name')),
                ('type', models.CharField(default='Apparel', max_length=100, verbose_name='type / apparel class')),
                ('category', models.CharField(default='General', max_length=100, verbose_name='category')),
                ('regular_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='regular price')),
                ('member_price', models.DecimalField(decimal_places=2, default=350.0, max_digits=10, verbose_name='member price')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.TextField(blank=True, default='https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80', verbose_name='product image url')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='featured tag')),
                ('size_stock', models.JSONField(blank=True, default=dict, help_text='JSON map of size to available quantity, e.g. {"S": 12, "M": 24, "L": 18}', verbose_name='stock per size map')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Merchandise Product',
                'verbose_name_plural': 'Merchandise Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='currency')),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=100, verbose_name='razorpay order ID')),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='razorpay payment ID')),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, verbose_name='razorpay signature')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20, verbose_name='status')),
                ('payment_type', models.CharField(choices=[('EVENT_TICKET', 'Event Ticket'), ('MERCHANDISE', 'Merchandise'), ('MEMBERSHIP', 'Membership')], default='EVENT_TICKET', max_length=30, verbose_name='payment type')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='extra payment metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchandiseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='order ID')),
                ('variant', models.CharField(default='M', max_length=50, verbose_name='size / variant')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='unit price')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total amount')),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='order status')),
                ('collection_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('READY_FOR_COLLECTION', 'Ready for Collection'), ('COLLECTED', 'Collected')], db_index=True, default='PENDING', max_length=30, verbose_name='collection status')),
                ('qr_token', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True, verbose_name='secure collection QR token')),
                ('qr_code', models.FileField(blank=True, null=True, upload_to='merchandise/qr/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='merchandise/pdf/')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='collected at timestamp')),
                ('pickup_location', models.CharField(default='Student Union Desk - Campus Hub', max_length=255, verbose_name='pickup location')),
                ('notes', models.TextField(blank=True, verbose_name='notes / fulfillment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandise_orders', to=settings.AUTH_USER_MODEL)),
                ('merchandise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='finance.merchandiseproduct')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchandise_orders', to='finance.payment')),
            ],
            options={
                'verbose_name': 'Merchandise Order',
                'verbose_name_plural': 'Merchandise Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='finance_pay_razorpa_ab09a4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_payment_id'], name='finance_pay_razorpa_18189b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='finance_pay_status_cb601d_idx'),
        ),
    ]
