# Generated by Django 6.0.2 on 2026-10-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_enhance_finance_ledger'),
        ('finance', '0002_merchandiseproduct_payment_merchandiseorder_and_more'),
    ]

    operations = [
    ]
