# Generated by Django 6.0.2 on 2026-10-03 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_merge_20261004_0326'),
        ('volunteers', '0008_ticket_checked_in_ticket_checked_in_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_razorpa_ab09a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_razorpa_18189b_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed at'),
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='volunteers.event'),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchandise_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payments', to='finance.merchandiseorder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('DEMO', 'Demo / Simulated'), ('RAZORPAY', 'Razorpay Gateway'), ('OFFLINE', 'Offline / Cash')], db_index=True, default='DEMO', max_length=20, verbose_name='payment mode'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_payments', to='volunteers.ticket'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='transaction ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('EVENT_TICKET', 'Event Ticket'), ('MERCHANDISE', 'Merchandise'), ('MEMBERSHIP', 'Membership'), ('DONATION', 'Donation'), ('OTHER_PURCHASE', 'Other Purchase')], db_index=True, default='EVENT_TICKET', max_length=30, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='razorpay order ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='finance_pay_transac_c95172_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_mode'], name='finance_pay_payment_646e82_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='finance_pay_payment_511934_idx'),
        ),
    ]
